// SQUELETTE — port de E5_HybAS.cls à réaliser (source VBA : vba-source/E5_HybAS.cls).
// Les paramètres ci-dessous sont les cellules de valeurs forcées (CelVF_*) du bloc
// correspondant de l'onglet Calculs ; le calcul laisse l'eau inchangée tant que
// compute() n'est pas porté.
import { passthrough } from './_stub.js'

export default passthrough({
  id: "hybas",
  label: "HybAS",
  short: "HybAS",
  family: "secondaire",
  vba: "E5_HybAS.cls",
  description: "Procédé hybride boue activée + média (HYBAS) : pré-anoxie, anaérobie, pré-dénit, déox, cuves aérées à média, réox, post-dénit.",
  params: [
    { key: "recirculation_taux", label: "Taux de recirculation des boues du clarificateur", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "recirculation_P_refoulement", label: "Pression de refoulement de la recirculation des boues du clarificateur", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "recirculation_pompe_rdt", label: "Rendement global des pompes de recirculation des boues (machine+moteur)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_NH4", label: "Concentration N-NH4+ sortie", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_NO3", label: "Concentration N-NO3- sortie", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "pre_denit_NO3", label: "Concentration N-NO3- en sortie de Pré-Dénitrification", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "NO3_last_aerated_tank", label: "Concentration NNO3- dernier tank aéré", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "Norga_dure_soluble", label: "Norga dure et soluble", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_DBO_soluble", label: "Concentration DBO soluble en sortie", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_MES_concentration", label: "Concentration en MES dans les bassins", unit: "g/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_MV_MES", label: "Pourcentage MV/MES", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_recirculation_MLSS_taux", label: "Taux de recirculation de la liqueur mixte", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "reel_MES_concentration", label: "Concentration en MES dans les bassins", unit: "g/L", group: 'Valeurs forcées', default: undefined },
    { key: "reel_MV_MES", label: "Pourcentage MV/MES", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "reel_recirculation_MLSS_taux", label: "Taux de recirculation de la liqueur mixte", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "recirculation_MLSS_P_refoulement", label: "Pression de refoulement de la recirculation de la liqueur mixte", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "recirculation_MLSS_pompe_rdt", label: "Rendement global pompes de recirculation de liqueur mixte (machine+moteur)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "pre_anoxie_volume", label: "Volume de la cuve de Pré-Anoxie", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "anaerobie_volume", label: "Volume de la cuve Anaérobie", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "anaerobie_FeCl3_flux", label: "Consommation de FeCl3 pur", unit: "kg/j", group: 'Valeurs forcées', default: undefined },
    { key: "pre_denit_volume", label: "Volume de la cuve de Pré-DN", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "deox_O2_dissous", label: "Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "deox_volume", label: "Volume de la cuve de Dé-Ox", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "reox_O2_dissous", label: "Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "reox_volume", label: "Volume de la cuve de Ré-Ox", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "reox_O2_alpha", label: "Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire)", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "reox_O2_rdt_transfert", label: "Rendement de transfert de l'oxygène", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "reox_hauteur_bassin", label: "Hauteur d'eau du bassin", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "post_denit_methanol_flux", label: "Consommation de méthanol", unit: "kg/j", group: 'Valeurs forcées', default: undefined },
    { key: "post_denit_media_filling", label: "Taux de remplissage", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "post_denit_volume", label: "Volume de la cuve de PostDN", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_Nnit_media_Nnit_total", label: "NH4 traité sur le média / NH4 traité dans les cuves (\"HybAS\" + DéOx)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_Nnit_mediaH1_Nnit_media", label: "NH4 traité sur média dans H1 / NH4 traité sur média", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_Nnit_CN1_Nnit_CN12", label: "NH4 traité dans C/N1 / NH4 traité dans (C/N1+C/N2)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_filling_1", label: "Taux de remplissage", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_dissous_1", label: "Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_volume_1", label: "Volume de la cuve", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_alpha_1", label: "Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire)", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_rdt_transfert_1", label: "Rendement de transfert de l'oxygène", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_hauteur_bassin_1", label: "Hauteur d'eau du bassin", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_filling_2", label: "Taux de remplissage", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_dissous_2", label: "Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_volume_2", label: "Volume de la cuve", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_alpha_2", label: "Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire)", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_rdt_transfert_2", label: "Rendement de transfert de l'oxygène", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_hauteur_bassin_2", label: "Hauteur d'eau du bassin", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_filling_3", label: "Taux de remplissage", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_dissous_3", label: "Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_volume_3", label: "Volume de la cuve", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_alpha_3", label: "Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire)", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_O2_rdt_transfert_3", label: "Rendement de transfert de l'oxygène", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_aeree_hauteur_bassin_3", label: "Hauteur d'eau du bassin", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "volume_total_bassins", label: "Volume total des bassins", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_reel_DBO", label: "Concentration en DBO5 en sortie (charges réelles)", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_reel_NH4", label: "Concentration en NNH4 en sortie (charges réelles)", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_reel_NO3", label: "Concentration en NNO3 en sortie (charges réelles)", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elec_pre_anoxie", label: "Ratio moyen d'agitation dans la cuve Pré-Anoxie", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elec_anaerobie", label: "Ratio moyen d'agitation dans la cuve Anaérobie", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elec_pre_denit", label: "Ratio moyen d'agitation dans la cuve Pré-Dénit", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elec_deox", label: "Ratio moyen d'agitation dans la cuve Dé-Ox", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elec_post_denit", label: "Ratio électrique d'agitation dans la cuve Post-Dénit", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "O2_besoin_total", label: "Besoin total en oxygène", unit: "kg O2/j", group: 'Valeurs forcées', default: undefined },
    { key: "air_Q_Nm3j", label: "Débit d'air process refoulé", unit: "Nm³/j", group: 'Valeurs forcées', default: undefined },
    { key: "diffuseur_encrassement", label: "Durée depuis l'installation / le dernier nettoyage des diffuseurs", unit: "an(s)", group: 'Valeurs forcées', default: undefined },
    { key: "air_P_refoulement_moyenne", label: "Pression de refoulement des surpresseurs", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "surpresseur_conso_spec", label: "Consommation électrique spécifique des surpresseurs", unit: "Wh/(Nm³.mCE)", group: 'Valeurs forcées', default: undefined },
    { key: "boues_indice_Mohlman", label: "Indice de boues", unit: "mL/g", group: 'Valeurs forcées', default: undefined },
    { key: "sortie_MES", label: "Concentration en MES de l'effluent", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "clarif_hauteur", label: "Hauteur du clarificateur", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "clarif_vitesse_max", label: "Vitesse hydraulique maximale", unit: "m/h", group: 'Valeurs forcées', default: undefined },
    { key: "clarif_surface", label: "Surface de décantation", unit: "m²", group: 'Valeurs forcées', default: undefined },
    { key: "clarif_vitesse_max_recalc", label: "Vitesse hydraulique maximale recalculée", unit: "m/h", group: 'Valeurs forcées', default: undefined },
    { key: "clarif_charge_radier_nominal", label: "Charge au radier (au nominal)", unit: "kg/(m².h)", group: 'Valeurs forcées', default: undefined },
    { key: "boues_concentration", label: "Concentration en MES des boues extraites", unit: "g/L", group: 'Valeurs forcées', default: undefined },
    { key: "boues_MES", label: "Boues à extraire", unit: "kg MES/j", group: 'Valeurs forcées', default: undefined },
    { key: "boues_Q", label: "m³/j", unit: "#REF!", group: 'Valeurs forcées', default: undefined },
    { key: "extraction_P_refoulement", label: "Pression de refoulement de l'extraction", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "extraction_pompe_rdt", label: "Rendement global des pompes d'extraction (machine+moteur)", unit: "%", group: 'Valeurs forcées', default: undefined },
  ],
})
