// SQUELETTE — port de E6_MBBR.cls à réaliser (source VBA : vba-source/E6_MBBR.cls).
// Les paramètres ci-dessous sont les cellules de valeurs forcées (CelVF_*) du bloc
// correspondant de l'onglet Calculs ; le calcul laisse l'eau inchangée tant que
// compute() n'est pas porté.
import { passthrough } from './_stub.js'

export default passthrough({
  id: "mbbr",
  label: "MBBR",
  short: "MBBR",
  family: "secondaire",
  vba: "E6_MBBR.cls",
  description: "Réacteur à lit mobile (MBBR) : cuves pré-dénit, cuves carbone, cuves nitrification, post-dénit, agitation et aération par cuve.",
  params: [
    { key: "nominal_outlet_DBO_mgL", label: "Concentration en DBO5 en sortie", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_outlet_NH4_mgL", label: "Concentration N-NH4+ sortie", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_outlet_NO3_mgL", label: "Concentration N-NO3- sortie", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "Norga_dure_soluble", label: "Norga dure et soluble", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_predenit_NO3_mgL", label: "Concentration N-NO3- en sortie de Pré-Dénitrification", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_last_aerated_tank_NO3_mgL", label: "Concentration en N-NO3 avant la post-dénit", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "nominal_recirculation_MLSS_taux", label: "Taux de recirculation de la liqueur mixte", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "reel_recirculation_MLSS_taux", label: "Taux de recirculation de la liqueur mixte", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "recirculation_MLSS_P_refoulement", label: "Pression de refoulement de la recirculation de la liqueur mixte", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "recirculation_MLSS_pompe_rdt", label: "Rendement global pompes de recirculation de liqueur mixte (machine+moteur)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elimination_predenit1_predenit12", label: "Répartition des charges éliminées cuve 1 / (cuves 1 et 2)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_1", label: "Taux de remplissage cuve 1", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_1", label: "Volume de la cuve 1", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_ratio_agitation_W_m3_1", label: "   Ratio de consommation électrique dû à l'agitation", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_2", label: "Taux de remplissage cuve 2", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_2", label: "Volume de la cuve 2", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_ratio_agitation_W_m3_2", label: "   Ratio de consommation électrique dû à l'agitation", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elimination_C1_C12", label: "Répartition des charges éliminées cuve 1 / (cuves 1 et 2)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_3", label: "  Taux de remplissage cuve 1", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_dissous_3", label: "  Concentration en O2 dissous dans la cuve 1", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_3", label: "  Volume de la cuve 1", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_facteur_alfa_3", label: "  Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire) 1", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_rdt_transfert_3", label: "  Rendement de transfert de l'oxygène dans la cuve 1", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_hauteur_3", label: "  Hauteur d'eau de la cuve1", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_Qair_1", label: "  Débit d'air surfacique à insuffler pour brasser la cuve 1", unit: "Nm³/(m².h)", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_air_hj_1", label: "  Durée journalière de suraération pour le brassage de la cuve 1", unit: "h/j", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_mecanique_Wm3_1", label: "  Ratio d'agitation mécanique de la cuve 1 ramené à un fonctionnement de 24h/j", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_4", label: "  Taux de remplissage cuve 2", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_dissous_4", label: "  Concentration en O2 dissous dans la cuve 2", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_4", label: "  Volume de la cuve 2", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_facteur_alfa_4", label: "  Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire) 2", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_rdt_transfert_4", label: "  Rendement de transfert de l'oxygène dans la cuve 2", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_hauteur_4", label: "  Hauteur d'eau de la cuve2", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_Qair_2", label: "  Débit d'air surfacique à insuffler pour brasser la cuve 2", unit: "Nm³/(m².h)", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_air_hj_2", label: "  Durée journalière de suraération pour le brassage de la cuve 2", unit: "h/j", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_mecanique_Wm3_2", label: "  Ratio d'agitation mécanique de la cuve 2 ramené à un fonctionnement de 24h/j", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elimination_N1_N12", label: "Répartition des charges éliminées cuve 1 / (cuves 1 et 2)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_5", label: "    Taux de remplissage cuve 1", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_dissous_5", label: "    Concentration en O2 dissous dans la cuve 1", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_5", label: "    Volume de la cuve 1", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_facteur_alfa_5", label: "    Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire) 1", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_rdt_transfert_5", label: "    Rendement de transfert de l'oxygène dans la cuve 1", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_hauteur_5", label: "    Hauteur d'eau de la cuve1", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_Qair_3", label: "  Débit d'air surfacique à insuffler pour brasser la cuve 1", unit: "Nm³/(m².h)", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_air_hj_3", label: "  Durée journalière de suraération pour le brassage de la cuve 1", unit: "h/j", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_mecanique_Wm3_3", label: "  Ratio d'agitation mécanique de la cuve 1 ramené à un fonctionnement de 24h/j", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_6", label: "    Taux de remplissage cuve 2", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_dissous_6", label: "    Concentration en O2 dissous dans la cuve 2", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_6", label: "    Volume de la cuve 2", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_facteur_alfa_6", label: "    Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire) 2", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_rdt_transfert_6", label: "    Rendement de transfert de l'oxygène dans la cuve 2", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_hauteur_6", label: "    Hauteur d'eau de la cuve2", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_Qair_4", label: "  Débit d'air surfacique à insuffler pour brasser la cuve 2", unit: "Nm³/(m².h)", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_air_hj_4", label: "  Durée journalière de suraération pour le brassage de la cuve 2", unit: "h/j", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_mecanique_Wm3_4", label: "  Ratio d'agitation mécanique de la cuve 2 ramené à un fonctionnement de 24h/j", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_7", label: "Taux de remplissage", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_dissous_7", label: "Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_7", label: "Volume de la cuve", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_ratio_agitation_W_m3_7", label: "   Ratio de consommation électrique dû à l'agitation", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "ratio_elimination_postdenit1_postdenit12", label: "Répartition des charges éliminées cuve 1 / (cuves 1 et 2)", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "postdenit_carbone_apporte_flux", label: "Consommation de méthanol", unit: "kg/j", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_8", label: "    Taux de remplissage cuve 1", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_8", label: "    Volume de la cuve 1", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_ratio_agitation_W_m3_8", label: "   Ratio de consommation électrique dû à l'agitation", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_9", label: "    Taux de remplissage cuve 2", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_9", label: "    Volume de la cuve 2", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_ratio_agitation_W_m3_9", label: "   Ratio de consommation électrique dû à l'agitation", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_filling_10", label: "  Taux de remplissage", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_dissous_10", label: "  Concentration en O2 dissous", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_volume_10", label: "  Volume de la cuve", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_facteur_alfa_10", label: "  Facteur alpha (transfert O2 en eaux usées / transfert O2 en eau claire)", unit: "-", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_O2_rdt_transfert_10", label: "  Rendement de transfert de l'oxygène", unit: "%/m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_hauteur_10", label: "  Hauteur d'eau du bassin", unit: "m", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_Qair_5", label: "  Débit d'air surfacique à insuffler pour brasser la cuve", unit: "Nm³/(m².h)", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_air_hj_5", label: "  Durée journalière de suraération pour le brassage de la cuve", unit: "h/j", group: 'Valeurs forcées', default: undefined },
    { key: "cuve_brassage_mecanique_Wm3_5", label: "  Ratio d'agitation mécanique de la cuve ramené à un fonctionnement de 24h/j", unit: "W/m³", group: 'Valeurs forcées', default: undefined },
    { key: "volume_total_bassins", label: "Volume total des bassins", unit: "m³", group: 'Valeurs forcées', default: undefined },
    { key: "reel_outlet_DBO_mgL", label: "Concentration en DBO5 en sortie (charges réelles)", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "reel_outlet_NH4_mgL", label: "Concentration en NNH4 en sortie (charges réelles)", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "reel_outlet_NO3_mgL", label: "Concentration en NNO3 en sortie (charges réelles)", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "O2_besoin_total", label: "Besoin total en oxygène", unit: "kg O2/j", group: 'Valeurs forcées', default: undefined },
    { key: "air_Q_Nm3j", label: "Débit d'air process refoulé", unit: "Nm³/j", group: 'Valeurs forcées', default: undefined },
    { key: "diffuseur_encrassement", label: "Durée depuis l'installation / le dernier nettoyage des diffuseurs", unit: "an(s)", group: 'Valeurs forcées', default: undefined },
    { key: "air_P_refoulement_moyenne", label: "Pression de refoulement des surpresseurs", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "surpresseur_conso_spec", label: "Consommation électrique spécifique des surpresseurs", unit: "Wh/(Nm³.mCE)", group: 'Valeurs forcées', default: undefined },
    { key: "outlet_MES_concentration", label: "Concentration en MES de l'effluent", unit: "mg/L", group: 'Valeurs forcées', default: undefined },
    { key: "boues_concentration", label: "Concentration en MES des boues extraites", unit: "g/L", group: 'Valeurs forcées', default: undefined },
    { key: "boues_MES", label: "Boues à extraire", unit: "kg MES/j", group: 'Valeurs forcées', default: undefined },
    { key: "boues_MV_MES", label: "Pourcentage MV/MES", unit: "%", group: 'Valeurs forcées', default: undefined },
    { key: "extraction_P_refoulement", label: "Pression de refoulement de l'extraction", unit: "mCE", group: 'Valeurs forcées', default: undefined },
    { key: "extraction_pompe_rdt", label: "Rendement global des pompes d'extraction (machine+moteur)", unit: "%", group: 'Valeurs forcées', default: undefined },
  ],
})
